# Generated by Django 5.1.6 on 2025-02-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='username',
            new_name='Username',
        ),
    ]
