# Generated by Django 5.1.6 on 2025-03-01 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0004_rename_username_buyer_new_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='New_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_description', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('banner', models.ImageField(upload_to='')),
                ('gstin', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=400)),
                ('New_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
