# Generated by Django 5.1.6 on 2025-03-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecommerce_Website_Application", "0005_alter_buyer_new_user_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="banner",
            field=models.ImageField(
                default="", upload_to="Ecommerce_Website_Application/Shop/Banners"
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="logo",
            field=models.ImageField(
                default="", upload_to="Ecommerce_Website_Application/Shop/Logos"
            ),
        ),
    ]
