# Generated by Django 5.1.6 on 2025-03-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecommerce_Website_Application", "0006_alter_seller_banner_alter_seller_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="banner",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="seller",
            name="logo",
            field=models.ImageField(upload_to=""),
        ),
    ]
