# Generated by Django 5.1.6 on 2025-03-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0008_alter_seller_banner_alter_seller_gstin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('catedory_discription', models.CharField(max_length=100)),
                ('category_logo', models.ImageField(upload_to='C_Logos/')),
                ('category_banner', models.ImageField(upload_to='C_Banners/')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=1)),
                ('product_img', models.ImageField(upload_to='Products_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_Website_Application.category')),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_Website_Application.seller')),
            ],
        ),
    ]
