# Generated by Django 5.1.6 on 2025-03-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Ecommerce_Website_Application",
            "0010_rename_catedory_discription_category_catedory_description",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="catedory_description",
            new_name="category_description",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="category_name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="category_name",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_logo",
        ),
        migrations.AddField(
            model_name="category",
            name="category_icon",
            field=models.ImageField(default="", upload_to="Categories/Icons/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_banner",
            field=models.ImageField(default="", upload_to="Categories/Banners/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_img",
            field=models.ImageField(upload_to="Products/Images"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="banner",
            field=models.ImageField(upload_to="Sellers/Banners/"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="logo",
            field=models.ImageField(upload_to="Sellers/Logos/"),
        ),
    ]
