# Generated by Django 5.1.6 on 2025-03-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
