# Generated by Django 5.1.6 on 2025-03-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0016_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Placed', 'Ordered_Placed'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Out For Pickup', 'Out_For_Pickup'), ('Picked Up', 'Picked_Up'), ('Out For Delivery', 'Out_For_Delivery'), ('Delivered', 'Delivered')], default='Order Placed', max_length=50),
        ),
    ]
