# Generated by Django 5.1.6 on 2025-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0017_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('In Stock', 'In_Stock'), ('Out of Stock', 'Out_of_Stock')], default='In Stock', max_length=50),
        ),
    ]
