# Generated by Django 5.1.6 on 2025-03-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0019_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[(True, 'In_Stock'), (False, 'Out_of_Stock')], default=True, max_length=50),
        ),
    ]
