# Generated by Django 5.1.6 on 2025-03-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0021_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('In_Stock', 'In Stock'), ('Out_of_Stock', 'Out of Stock')], default='Out_of_Stock', max_length=50),
        ),
    ]
