# Generated by Django 5.1.6 on 2025-03-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0024_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_status',
            field=models.BooleanField(default=False),
        ),
    ]
