# Generated by Django 5.1.6 on 2025-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0025_order_buyer_status_order_seller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('purpose', models.TextField(max_length=500)),
            ],
        ),
    ]
