# Generated by Django 5.1.6 on 2025-03-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website_Application', '0026_contact_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Requests',
            new_name='Contact_Request',
        ),
    ]
